import { ThemeProvider } from '@/components/themes-provider';
import { Avatar, AvatarImage } from '@/components/ui/avatar';
import { Menubar, MenubarMenu, MenubarTrigger } from '@/components/ui/menubar';
import { ThemeSwitch } from '@/components/ui/theme-switch';
import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import Link from 'next/link';
import './globals.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const menuItems = [
  { label: 'About', value: '/' },
  {
    label: 'Projects',
    value: '/projects',
  },
  {
    label: 'Skills',
    value: '/skills',
  },
];

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <div className="w-full h-screen">
            <div className="mx-auto w-full h-full max-w-screen-xl px-6 pb-32 pt-12 md:px-12 lg:max-w-6xl lg:py-0">
              <header className="flex items-center justify-between w-full px-5 h-12 bg-slate-200 pt-8">
                <Avatar>
                  <AvatarImage src="https://github.com/shadcn.png" />
                </Avatar>
                <Menubar>
                  {menuItems.map((item, index) => (
                    <MenubarMenu key={index}>
                      <MenubarTrigger>
                        <Link href={`${item.value}`}>{item.label}</Link>
                      </MenubarTrigger>
                    </MenubarMenu>
                  ))}
                </Menubar>
                <ThemeSwitch />
              </header>
              {children}
            </div>
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
