import { ThemeProvider } from '@/components/themes-provider';
import { Avatar, AvatarImage } from '@/components/ui/avatar';
import Navigator from '@/components/ui/navigator';
import { ScrollArea } from '@/components/ui/scroll-area';
import { ThemeSwitch } from '@/components/ui/theme-switch';
import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const menuItems = [
  { label: 'About', value: '/' },
  {
    label: 'Projects',
    value: '/projects',
  },
  {
    label: 'Skills',
    value: '/skills',
  },
];

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <div className="w-full h-screen">
            <ScrollArea className="w-full h-full">
              <div className="h-full flex flex-col max-w-[1220px] mx-auto bg-background border">
                <header className="absolute top-3 left-1/2 transform -translate-x-1/2 w-full max-w-[1220px] flex bg-transparent px-20 py-2">
                  <div className="flex-grow justify-start">
                    <Avatar>
                      <AvatarImage
                        src="https://github.com/shadcn.png"
                        alt="@shadcn"
                      />
                    </Avatar>
                  </div>
                  <div className="flex-grow flex justify-center">
                    <Navigator />
                  </div>
                  <div className="flex-grow flex justify-end">
                    <ThemeSwitch />
                  </div>
                </header>
                <div className="flex-grow h-full">{children}</div>
              </div>
            </ScrollArea>
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
